# Generated by ariadne-codegen
# Source: vals/graphql/

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class AddOrRemoveUsersToRunReview(BaseModel):
    update_assigned_reviewers: Optional[
        "AddOrRemoveUsersToRunReviewUpdateAssignedReviewers"
    ] = Field(alias="updateAssignedReviewers")


class AddOrRemoveUsersToRunReviewUpdateAssignedReviewers(BaseModel):
    single_test_reviews: List[
        "AddOrRemoveUsersToRunReviewUpdateAssignedReviewersSingleTestReviews"
    ] = Field(alias="singleTestReviews")


class AddOrRemoveUsersToRunReviewUpdateAssignedReviewersSingleTestReviews(BaseModel):
    id: Any


AddOrRemoveUsersToRunReview.model_rebuild()
AddOrRemoveUsersToRunReviewUpdateAssignedReviewers.model_rebuild()
