# Generated by ariadne-codegen
# Source: vals/graphql/

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class AddAllTestsToQueueSingle(BaseModel):
    add_all_single_test_review_to_queue: Optional[
        "AddAllTestsToQueueSingleAddAllSingleTestReviewToQueue"
    ] = Field(alias="addAllSingleTestReviewToQueue")


class AddAllTestsToQueueSingleAddAllSingleTestReviewToQueue(BaseModel):
    single_test_reviews: List[
        "AddAllTestsToQueueSingleAddAllSingleTestReviewToQueueSingleTestReviews"
    ] = Field(alias="singleTestReviews")


class AddAllTestsToQueueSingleAddAllSingleTestReviewToQueueSingleTestReviews(BaseModel):
    id: Any


AddAllTestsToQueueSingle.model_rebuild()
AddAllTestsToQueueSingleAddAllSingleTestReviewToQueue.model_rebuild()
