# Generated by ariadne-codegen
# Source: vals/graphql/

from typing import Any, Dict

from .async_base_client import AsyncBaseClient
from .get_test_suite_data import GetTestSuiteData


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def get_test_suite_data(
        self, suite_id: str, **kwargs: Any
    ) -> GetTestSuiteData:
        query = gql(
            """
            query getTestSuiteData($suiteId: String!) {
              testSuites(testSuiteId: $suiteId) {
                description
                id
                org
                title
                created
                globalChecks
              }
            }
            """
        )
        variables: Dict[str, object] = {"suiteId": suite_id}
        response = await self.execute(
            query=query,
            operation_name="getTestSuiteData",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetTestSuiteData.model_validate(data)
