# Generated by ariadne-codegen
# Source: vals/graphql/

from datetime import datetime
from typing import Any

from pydantic import Field

from .base_model import BaseModel


class DefaultProject(BaseModel):
    default_project: "DefaultProjectDefaultProject" = Field(alias="defaultProject")


class DefaultProjectDefaultProject(BaseModel):
    id: Any
    name: str
    slug: str
    created: datetime
    is_default: bool = Field(alias="isDefault")


DefaultProject.model_rebuild()
