# Generated by ariadne-codegen
# Source: http://localhost:8000/graphql/

from enum import Enum


class RunReviewStatusEnum(str, Enum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"
    CANCELLED = "CANCELLED"


class AppQuestionAnswerSetCreationMethodChoices(str, Enum):
    LIVE_QUERY = "LIVE_QUERY"
    SDK = "SDK"
    UPLOAD = "UPLOAD"


class RunStatus(str, Enum):
    IN_PROGRESS = "IN_PROGRESS"
    ERROR = "ERROR"
    SUCCESS = "SUCCESS"
    RERUNNING = "RERUNNING"


class TestResultReviewStatusEnum(str, Enum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"


class RunReviewTableSortField(str, Enum):
    CREATED_AT = "CREATED_AT"
    COMPLETED_TIME = "COMPLETED_TIME"
    STATUS = "STATUS"


class SortOrder(str, Enum):
    ASC = "ASC"
    DESC = "DESC"


class TestSuiteSortField(str, Enum):
    TITLE = "TITLE"
    CREATED = "CREATED"
    LAST_MODIFIED_AT = "LAST_MODIFIED_AT"


class RunResultSortField(str, Enum):
    NAME = "NAME"
    STARTED_AT = "STARTED_AT"
    COMPLETED_AT = "COMPLETED_AT"
    PASS_PERCENTAGE = "PASS_PERCENTAGE"


class TierEnum(str, Enum):
    FREE = "FREE"
    STARTUP = "STARTUP"
    ENTERPRISE = "ENTERPRISE"


class TestResultReviewSortField(str, Enum):
    STARTED_AT = "STARTED_AT"
    STATUS = "STATUS"
    COMPLETED_AT = "COMPLETED_AT"
