# Generated by ariadne-codegen
# Source: vals/graphql/

from datetime import datetime
from typing import Any

from pydantic import Field

from .base_model import BaseModel


class GetTestSuiteData(BaseModel):
    test_suite: "GetTestSuiteDataTestSuite" = Field(alias="testSuite")


class GetTestSuiteDataTestSuite(BaseModel):
    description: str
    id: str
    project: "GetTestSuiteDataTestSuiteProject"
    org: str
    title: str
    created: datetime
    global_checks: Any = Field(alias="globalChecks")


class GetTestSuiteDataTestSuiteProject(BaseModel):
    slug: str


GetTestSuiteData.model_rebuild()
GetTestSuiteDataTestSuite.model_rebuild()
