base-config:
  company: Amazon
  open_source: false
  class_properties:
    supports_images: false
    available_as_evaluator: false
    supports_metadata: true
    supports_files: false
    available_for_everyone: true
  properties:
    reasoning_model: false
nova-models:
  base-config:
    documentation_url: https://www.aboutamazon.com/news/aws/amazon-nova-artificial-intelligence-bedrock-aws

  amazon/amazon.nova-pro-v1:0:
    label: Nova Pro
    description: Nova Pro is a multimodal understanding foundation model. It is multilingual and can reason over text, images and videos.
    release_date: "2024-12-03"
    properties:
      context_window: 300_000
      max_token_output: null
      training_cutoff: null
    class_properties:
      supports_images: true
    costs_per_million_token:
      input: 0.8
      output: 3.2

  amazon/amazon.nova-lite-v1:0:
    label: Nova Lite
    description: Nova Lite is a multimodal understanding foundation model. It is multilingual and can reason over text, images and videos.
    release_date: "2024-12-03"
    properties:
      context_window: 300_000
      max_token_output: null
      training_cutoff: null
    class_properties:
      supports_images: true
    costs_per_million_token:
      input: 0.06
      output: 0.24

  amazon/amazon.nova-micro-v1:0:
    label: Nova Micro
    description: Nova Micro is a multimodal understanding foundation model. It is multilingual and can reason over text, images and videos.
    release_date: "2024-12-03"
    properties:
      context_window: 128_000
      max_token_output: null
      training_cutoff: null
    costs_per_million_token:
      input: 0.035
      output: 0.14

claude-models:
  base-config:
    documentation_url: https://docs.anthropic.com/en/docs/models/claude-3-5-sonnet
  
  bedrock/claude-3-5-sonnet-20240620-v2:
    label: Claude 3.5 Sonnet (Bedrock)
    description: Claude 3.5 Sonnet is a multimodal understanding foundation model. It is multilingual and can reason over text, images and videos.
    release_date: "2024-10-22"
    properties:
      context_window: 100_000
      max_token_output: null
      training_cutoff: null
    class_properties:
      supports_images: false
      available_as_evaluator: true
      available_for_everyone: false
    provider_endpoint: us.anthropic.claude-3-5-sonnet-20241022-v2:0

  bedrock/claude-3-7-sonnet-20250219-v1:
    label: Claude 3.7 Sonnet (Bedrock)
    description: Claude 3.7 Sonnet, hosted on Bedrock.
    release_date: "2025-02-19"
    properties:
      context_window: 200_000
      max_token_output: null
      training_cutoff: null
    class_properties:
      supports_images: true
      available_as_evaluator: true
      available_for_everyone: false
    provider_endpoint: us.anthropic.claude-3-7-sonnet-20250219-v1:0

  bedrock/claude-3-5-haiku-20241022-v1:
    label: Claude 3.5 Haiku (Bedrock)
    description: Claude 3.5 Haiku, hosted on Bedrock.
    release_date: "2024-10-22"
    properties:
      context_window: 200_000
      max_token_output: null
      training_cutoff: null
    class_properties:
      supports_images: false
      available_for_everyone: false
    provider_endpoint: us.anthropic.claude-3-5-haiku-20241022-v1:0

  bedrock/deepseek-r1-v1:
    label: DeepSeek R1 (Bedrock)
    description: DeepSeek R1, hosted on Bedrock.
    release_date: "2025-03-03"
    properties:
      context_window: 128_000
      max_token_output: null
      training_cutoff: null
    class_properties:
      supports_images: false
      available_for_everyone: false
    provider_endpoint: us.deepseek.r1-v1:0

  bedrock/llama3-3-70b-instruct-v1:
    label: Llama 3.3 70B Instruct (Bedrock)
    description: Llama 3.3 70B Instruct, hosted on Bedrock.
    release_date: "2024-12-18"
    properties:
      context_window: 128_000
      max_token_output: null
      training_cutoff: null
    class_properties:
      supports_images: false
      available_as_evaluator: true
      available_for_everyone: false
    provider_endpoint: us.meta.llama3-3-70b-instruct-v1:0
