base-config:
  company: Anthropic
  open_source: false
  class_properties:
    available_as_evaluator: false
    supports_images: false
    supports_metadata: true
    supports_files: false
    available_for_everyone: true
  properties:
    reasoning_model: false
  

claude-4-models:
  base-config:
    class_properties:
      supports_images: true

  anthropic/claude-sonnet-4-20250514:
    label: Claude Sonnet 4 (Nonthinking)
    description: Anthropic's latest-generation workhorse model, offering a balance of performance and speed.
    release_date: "2025-05-22"
    documentation_url: https://www.anthropic.com/claude/sonnet
    properties:
      context_window: 200_000
      max_token_output: 64_000
      extending_thinking: 64_000
      training_cutoff: "2025-03"
    costs_per_million_token:
      input: 3.0
      output: 15.0

  anthropic/claude-opus-4-20250514:
    label: Claude Opus 4 (Nonthinking)
    description: Anthropic's most powerful model.
    release_date: "2025-05-22"
    properties:
      context_window: 200_000
      max_token_output: 64_000
      extending_thinking: 64_000
      training_cutoff: "2025-03"
    class_properties:
      available_for_everyone: false
    costs_per_million_token:
      input: 15.0
      output: 75.0

    
  anthropic/claude-sonnet-4-20250514-thinking:
    label: Claude Sonnet 4 (Thinking)
    description: Anthropic's latest-generation workhorse model, offering a balance of performance and speed.
    release_date: "2025-05-22"
    documentation_url: https://www.anthropic.com/claude/sonnet
    properties:
      context_window: 200_000
      max_token_output: 64_000
      extending_thinking: 64_000
      training_cutoff: "2025-03"
      reasoning_model: true
    costs_per_million_token:
      input: 3.0
      output: 15.0

  anthropic/claude-opus-4-20250514-thinking:
    label: Claude Opus 4 (Thinking)
    description: Anthropic's most powerful model.
    release_date: "2025-05-22"
    properties:
      context_window: 200_000
      max_token_output: 64_000
      extending_thinking: 64_000
      training_cutoff: "2025-03"
      reasoning_model: true
    class_properties:
      available_for_everyone: false
    costs_per_million_token:
      input: 15.0
      output: 75.0

# CLAUDE 3.7 MODELS
claude-3-7-models:
  base-config:
    class_properties:
      supports_images: true

  anthropic/claude-3-7-sonnet-20250219:
    label: Claude 3.7 Sonnet (Nonthinking)
    release_date: "2025-02-24"
    description: Anthropic's previous state-of-the-art model, prior to Claude 4's release.
    documentation_url: https://www.anthropic.com/claude/sonnet
    properties:
      context_window: 200_000
      max_token_output: 8_192
      extending_thinking: 64_000
      training_cutoff: "2024-08"
    costs_per_million_token:
      input: 3.0
      output: 15.0

  anthropic/claude-3-7-sonnet-20250219-thinking:
    label: Claude 3.7 Sonnet (Thinking)
    release_date: "2025-02-24"
    description:  Anthropic's previous state-of-the-art model, prior to Claude 4's release.
    documentation_url: https://www.anthropic.com/claude/sonnet
    properties:
      context_window: 200_000
      max_token_output: 8_192
      extending_thinking: 64_000
      training_cutoff: "2024-08"
      reasoning_model: true
    costs_per_million_token:
      input: 3.0
      output: 15.0

# CLAUDE 3-5 MODELS
claude-3-5-models:
  base-config:
    class_properties:
      supports_images: true

  anthropic/claude-3-5-sonnet-20241022:
    label: Claude 3.5 Sonnet Latest
    release_date: "2024-10-22"
    description: Anthropic's most intelligent model.
    documentation_url: https://www.anthropic.com/claude/sonnet
    properties:
      context_window: 200_000
      max_token_output: 8192
      training_cutoff: "2024-04"
    costs_per_million_token:
      input: 3.0
      output: 15.0
    class_properties:
      available_as_evaluator: true
    alternative_keys:
      - claude-3-5-sonnet-latest
      - claude-3.5-sonnet-latest

  anthropic/claude-3-5-sonnet-20240620:
    label: Claude 3.5 Sonnet
    release_date: "2024-06-20"
    description: null
    documentation_url: https://www.anthropic.com/claude/sonnet
    properties:
      context_window: 200_000
      max_token_output: 8192
    costs_per_million_token:
      input: 3.0
      output: 15.0
    alternative_keys:
      - claude-3.5-sonnet

  anthropic/claude-3-5-haiku-20241022:
    label: Claude 3.5 Haiku Latest
    release_date: "2024-10-22"
    description: Anthropic's fastest model.
    documentation_url: https://www.anthropic.com/claude/haiku
    properties:
      context_window: 200_000
      max_token_output: 8192
      training_cutoff: "2024-07"
    costs_per_million_token:
      input: 1.0
      output: 5.0
    class_properties:
      available_as_evaluator: true
      supports_images: false
    alternative_keys:
      - claude-3-5-haiku-latest
      - claude-3-5-haiku

# CLAUDE 3 MODELS
claude-3-models:
  base-config:
    class_properties:
      supports_images: true
      deprecated: true

  anthropic/claude-3-opus-20240229:
    label: Claude 3 Opus
    release_date: "2024-02-29"
    description: Powerful model for highly complex tasks.
    documentation_url: https://www.anthropic.com/claude
    properties:
      context_window: 200_000
      max_token_output: 4096
      training_cutoff: "2023-08"
    costs_per_million_token:
      input: 15.0
      output: 75.0
    class_properties:
      available_for_everyone: false
    alternative_keys:
      - claude-3-opus-latest
      - claude-3-opus

  anthropic/claude-3-sonnet-20240229:
    label: Claude 3 Sonnet
    release_date: "2024-02-29"
    description: Balance of intelligence and speed.
    documentation_url: https://www.anthropic.com/claude/sonnet
    properties:
      context_window: 200_000
      max_token_output: 4096
      training_cutoff: "2023-08"
    costs_per_million_token:
      input: 3.0
      output: 15.0
    alternative_keys:
      - claude-3-sonnet

  anthropic/claude-3-haiku-20240307:
    label: Claude 3 Sonnet
    release_date: "2024-02-29"
    description: Fastest and most compact model for near-instant responsiveness.
    documentation_url: https://www.anthropic.com/claude/haiku
    properties:
      context_window: 200_000
      max_token_output: 4096
      training_cutoff: "2023-08"
    costs_per_million_token:
      input: 0.25
      output: 1.25
    alternative_keys:
      - claude-3-haiku

# CLAUDE 2 MODELS

claude-2-models:
  anthropic/claude-2.1:
    label: Claude 2.1
    release_date: null
    description: Updated version of Claude 2 with improved accuracy.
    documentation_url: https://www.anthropic.com/claude
    properties:
      context_window: 200_000
      max_token_output: 4096
      training_cutoff: "Early 2023"
    costs_per_million_token:
      input: 8.00
      output: 24.00
    class_properties:
      available_for_everyone: false
      deprecated: true
    alternative_keys:
      - claude-2

  anthropic/claude-2.0:
    label: Claude 2
    release_date: null
    description: Predecessor to Claude 3, offering strong all-round performance.
    documentation_url: https://www.anthropic.com/claude
    properties:
      context_window: 100_000
      max_token_output: 4096
      training_cutoff: "Early 2023"
    class_properties:
      deprecated: true
    costs_per_million_token:
      input: 8.00
      output: 24.00
  
  # TO CORRECT
  anthropic/claude-1.3:
    label: Claude 1.3
    release_date: null
    description: "Predecessor to Claude 3, offering strong all-round performance."
    documentation_url: "https://www.anthropic.com/claude"
    properties:
      context_window: null
      max_token_output: null
      training_cutoff: null
    class_properties:
      deprecated: true
    costs_per_million_token:
      input: null
      output: null
    alternative_keys:
      - claude-1.3

  anthropic/claude-instant-1.2:
    label: Claude Instant 1.2
    release_date: null
    description: Our cheapest small and fast model, a predecessor of Claude Haiku.
    documentation_url: https://www.anthropic.com/claude
    properties:
      context_window: 100_000
      max_token_output: 4096
      training_cutoff: "Early 2023"
    class_properties:
      deprecated: true
    costs_per_million_token:
      input: 0.80
      output: 2.40
    alternative_keys:
      - claude-instant
